spring.application.name=msc-ms-users
server.port=8182
server.servlet.context-path=/ms-users
spring.datasource.url=jdbc:mysql://localhost:3306/msc_development
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
msc.app.version=0.0.1-Beta
msc.app.date.format=yyyy-MM-dd
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
msc.services.authentication.url=http://localhost:7180/authentication/api
msc.services.location.url=http://localhost:7181/ms-address/api
msc.services.minio.url=http://localhost:7183/ms-file/api
msc.security.secret-key=NDQxQlROR1NuY2JjMTVOVFZBeURzZk5saXVNdmNKUWtiTGo3eEtoeVdVVkJLanBvWHludFFwWEM2amxCaXBscw==
msc.security.algorithm=AES
msc.security.key=Y29udHJhc2VuaWFtYW1hbG9uYXF1ZSBuYWRpZSBzZXNhYmUjQCQl
msc.security.own.key=O2lb7XhSC0V+JgNQhqcuGA==
msc.security.header=msc-security-key-header
msc.security.allowed.consumers=msc-ui-web,msc-address
mac.queues=q.msc.users,q.msc.tests
spring.rabbitmq.username=VIFA
spring.rabbitmq.password=951002
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
logging.level.org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration=ERROR
queue.user=q.msc.users
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
loki.url=http://localhost:3100/loki/api/v1/push