package com.msc.ms.users.authentication;

import lombok.extern.slf4j.Slf4j;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpStatus;
import org.springframework.test.context.junit4.SpringRunner;

@SpringBootTest
@RunWith(SpringRunner.class)
@Slf4j
public class AuthenticationRemoteServiceTest {
    @Autowired
    private IAuthenticationService iAuthenticationService;

    public AuthenticationRemoteServiceTest() {
    }

    @Test
    public void testRemoteGenerationofPasswords() {
        final var size = 10;
        final var response = this.iAuthenticationService.getPassword(size);
        Assert.assertEquals(HttpStatus.OK, response.getStatusCode());
        final var password = response.getBody();
        final var  passwordSize = password.length();
        log.info("Password generated by service is: {} with a  size of : {}", password,passwordSize);
        Assert.assertEquals(size, passwordSize);
    }
}
